version: '3.4'

services:
  mongodatabase:
    container_name: mongodatabase
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db


  rabbitmqbroker:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmqbroker
    container_name: rabbitmqbroker
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 3
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq


  customerservice.api:
    command: npm start
    build: ./CustomerService
    environment:
      PORT: 4001
      DB_URI: mongodb://mongodatabase:27017/customerServiceDB
    depends_on:
      mongodatabase:
        condition: service_started
    ports:
      - 4001:4001
    links:
      - mongodatabase

  
  paymentservice.api:
    command: npm start
    build: ./PaymentService
    restart: on-failure
    environment:
      PORT: 4002
      DB_URI: mongodb://mongodatabase:27017/paymentServiceDB
      RABBIT_URI: amqp://guest:guest@rabbitmqbroker:5672
    depends_on:
      mongodatabase:
        condition: service_started
      rabbitmqbroker:
        condition: service_healthy
    ports:
      - 4002:4002
    links:
      - mongodatabase
      - rabbitmqbroker

  
  orderservice.api:
    command: npm start
    build: ./OrderService
    restart: on-failure
    environment:
      PORT: 4003
      DB_URI: mongodb://mongodatabase:27017/orderServiceDB
      RABBIT_URI: amqp://guest:guest@rabbitmqbroker:5672
    depends_on:
      mongodatabase:
        condition: service_started
      rabbitmqbroker:
          condition: service_healthy
    ports:
      - 4003:4003
    links:
      - mongodatabase
      - rabbitmqbroker


  productservice.api:
    command: npm start
    build: ./ProductService
    environment:
      PORT: 4004
      DB_URI: mongodb://mongodatabase:27017/productServiceDB
    depends_on:
      mongodatabase:
        condition: service_started
    ports:
      - 4004:4004

volumes:
  mongo_data:
